name: Nightly

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ARTIFACT_NAME: resume
  EN_BASENAME: resume_en_US
  PT_BR_BASENAME: resume_pt_BR

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      DATA_DIRECTORY: data
      OUTPUT_DIRECTORY: generated
      IMAGE: ghcr.io/garapatech/softworker:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      
      - name: Pull container image
        run: docker pull ${{ env.IMAGE }}
      
      - name: Run container
        run: |
          mkdir -p generated
          for basename in "${{ env.PT_BR_BASENAME }}" "${{ env.EN_BASENAME }}"; do
            docker run \
              --init \
              --rm \
              -v "${{ github.workspace }}/${{ env.DATA_DIRECTORY }}:/app/${{ env.DATA_DIRECTORY }}" \
              -v "${{ github.workspace }}/${{ env.OUTPUT_DIRECTORY }}:/app/${{ env.OUTPUT_DIRECTORY }}" \
              ${{ env.IMAGE }} \
              python -m softworker --language "${basename#resume_}" \
              ${{ env.DATA_DIRECTORY }}/"${basename}.json" \
              ${{ env.OUTPUT_DIRECTORY }}/"${basename}.pdf"
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.OUTPUT_DIRECTORY }}/${{ env.EN_BASENAME }}.pdf
            ${{ env.OUTPUT_DIRECTORY }}/${{ env.PT_BR_BASENAME }}.pdf
          if-no-files-found: error

  release:
    needs: [generate]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

      - name: Upsert release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly
          files: |
            ${{ env.EN_BASENAME }}.pdf
            ${{ env.PT_BR_BASENAME }}.pdf
          overwrite_files: true
